# Generated by Django 2.0.7 on 2018-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('Reg_Date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('isApproval', models.CharField(max_length=2)),
                ('Location', models.CharField(max_length=256, verbose_name='위치')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Rotation',
            fields=[
                ('no_Setting', models.IntegerField(primary_key=True, serialize=False)),
                ('Ro_Image', models.CharField(max_length=256)),
                ('Ro_text', models.CharField(max_length=4098)),
                ('Ro_video', models.CharField(max_length=4098)),
            ],
        ),
    ]
